/* eslint-disable no-undef */
/* global i18next, jqueryI18next, $ */

const resources = {
  en: {
    translation: {
      title: "Modular Homes",
      brand: "Modular Homes",
      nav: {
        home: "Home",
        projects: "Projects",
        services: "Services",
        constructions: "Constructions",
        contact: "Contact"
      },
      "hero": {
        "slide1": {
          "title": "Building Green Futures",
          "subtitle": "EcoMod Homes designs and delivers sustainable prefab houses using recycled materials and advanced 3D-printing.",
          "button": "Discover Our Projects"
        },
        "slide2": {
          "title": "Innovative, Affordable, Eco-Friendly",
          "subtitle": "Experience fast assembly, high quality, and minimal environmental impact—your dream home, ready in weeks.",
          "button": "Get a Quote"
        }
      },
      features: {
        headingSmall: "Features",
        headingMain: "Why modular?",
        card1: {
          title: "Rapid Construction",
          desc: "Modular homes go from factory floor to finished site in as little as 3–4 weeks."
        },
        card2: {
          title: "Superior Quality",
          desc: "Precision-built under controlled conditions for unbeatable consistency."
        },
        card3: {
          title: "Eco-Friendly & Cost-Effective",
          desc: "Built from recycled materials with minimal waste—saving you time and money."
        }
      },
      about: {
        headingSmall: "About",
        headingMain: "Our Story",
        paragraph1: "Founded in 2015 by a small team of architects and engineers, Modular Homes was created to challenge the high cost and long timelines of traditional construction. From our very first prototype, we focused on combining precision manufacturing with sustainable materials to deliver exceptional value. In our initial years, we delivered dozens of homes across the region while fine-tuning our design and assembly methods. This early success laid the foundation for steady growth and innovation.",
        paragraph2: "Our inspiration stemmed from witnessing the environmental impact and waste generated by conventional building sites. We saw an opportunity to rethink construction as an assembly-line process, reducing on-site labor and material overruns. By adopting recycled steel frames and low-carbon concrete panels, we minimized waste without compromising structural performance. This commitment to eco-friendly practices continues to guide every project we undertake.",
        paragraph3: "Over the last decade, we have consistently improved our factory processes with advanced automation and rigorous quality controls. We expanded our portfolio to include custom layouts, energy-efficient technologies, and smart-home integrations. Hundreds of satisfied homeowners have since moved into their modular homes faster and with fewer delays than ever before. Looking ahead, we remain dedicated to pushing the boundaries of sustainable design and customer experience."
      },
      "stats": {
        "clients": "112+",
        "clients_label": "Happy Homeowners",
        "projects": "85+",
        "projects_label": "Completed Projects",
        "support": "500+",
        "support_label": "Consulting Hours",
        "workers": "25",
        "workers_label": "Expert Team Members"
      },
      "projects": {
        "title": "Projects",
        "filter": {
          "all": "All",
          "family": "Family Homes",
          "tiny": "Tiny Homes",
          "beach": "Beach Retreats",
          "eco": "Eco Villas"
        }
      },
      benefits: {
        title: "Why Build Step-by-Step?",
        item1: {
          title: "Financial Flexibility",
          desc: "Rather than pre-paying a single turn-key contractor for the entire project, spreading your build out lets you manage your cashflow in stages. You start with foundation and shell assembly, then pause to reorder funds or renegotiate financing before moving on to interiors. An unfinished—but existing—structure holds far more borrowing power than “just an idea.”"
        },
        item2: {
          title: "Cost Efficiency",
          desc: "Turn-key packages carry hidden markups at every subcontract—design, site prep, utilities, finishes. By sourcing each step yourself, you choose the best bidder and control quality. Even better: tackle smaller tasks yourself to save on labor costs, and re-use or repurpose materials for an even leaner build."
        },
        item3: {
          title: "Quality & Specialization",
          desc: "“Jack-of-all-trades” contractors can’t match the expertise of a dedicated prefab panel or roof-truss manufacturer. We’ve mastered our production with advanced CAD/CAM tooling and precision controls—so you know every wall, beam and connector is up to spec. Likewise, hiring specialist electricians, plumbers and landscapers means every trade delivers its best work."
        },
        item4: {
          title: "Owner Control & Customization",
          desc: "You’re the ultimate project manager. Inspect foundation levels before assembly, photograph MEP rough-ins before drywall and confirm roof ties before insulation goes in. And when it comes to layout or finishes—flip floor plans, enlarge openings or mix your own trim palette. Building bit by bit means your home truly reflects your vision."
        }
      },
      tabs: {
        modisit: "Modisit",
        praesenti: "Praesenti",
        explica: "Explica",
        nostrum: "Nostrum"
      },
      services: {
        title: "Services",
        item1: {
          title: "Design & Planning",
          desc: "Custom architectural layouts and 3D models tailored to your site and budget."
        },
        item2: {
          title: "Factory Production",
          desc: "Precision manufacturing under controlled conditions for zero waste and high quality."
        },
        item3: {
          title: "On-Site Assembly",
          desc: "Full turnkey installation in days, handled by our certified construction team."
        },
        item4: {
          title: "Energy Certification",
          desc: "Consulting on passive design, solar integration, and low-energy operation."
        },
        item5: {
          title: "Smart Home Integration",
          desc: "Seamlessly integrate automation, security, and entertainment systems into your modular home."
        },
        item6: {
          title: "Customization Options",
          desc: "Choose bespoke layouts, finishes, and features tailored to your lifestyle and needs."
        }
      },
      constructions: {
        title: "Constructions",
        item1: { title: "Item One", desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit." }
      },
      footer: { copy: "© 2025 Modular Homes. All Rights Reserved." }
    }
  },
  hr: {
    translation: {
      title: "Modularne kuće",
      brand: "Modularne kuće",
      nav: {
        home: "Početna",
        projects: "Projekti",
        services: "Usluge",
        constructions: "Izgradnje",
        contact: "Kontakt"
      },
      "hero": {
        "slide1": {
          "title": "Gradimo Zelenu Budućnost",
          "subtitle": "EcoMod Homes dizajnira i isporučuje održive montažne kuće od recikliranih materijala i naprednog 3D-printanja.",
          "button": "Istražite Projekte"
        },
        "slide2": {
          "title": "Inovativno, Pristupačno, Eko",
          "subtitle": "Brza montaža, vrhunska kvaliteta i minimalan utjecaj na okoliš—vaš dom iz snova, gotov za tjedne.",
          "button": "Zatraži Ponudu"
        }
      },
      features: {
        headingSmall: "Značajke",
        headingMain: "Zašto odabrati montažne kuće?",
        subheading: "Otkrijte prednosti ekološkog i brzog montažnog stanovanja.",
        card1: {
          title: "Brza montaža",
          desc: "Montažne kuće iz tvornice stižu posložene na gradilištu za samo 3–4 tjedna."
        },
        card2: {
          title: "Vrhunska kvaliteta",
          desc: "Precizna izrada u kontroliranim uvjetima za dosljedne rezultate."
        },
        card3: {
          title: "Eko i isplativo",
          desc: "Izrađene od recikliranih materijala uz minimalni otpad—štedite vrijeme i novac."
        }
      },
      about: {
        headingSmall: "O nama",
        headingMain: "Naša priča",
        paragraph1: "Osnovani 2015. godine od male grupe arhitekata i inženjera, Modular Homes nastao je kako bi izazvao visoke troškove i duge rokove tradicionalne gradnje. Od samog prvog prototipa, fokusirali smo se na kombinaciju precizne proizvodnje i održivih materijala kako bismo isporučili izvrsnu vrijednost. U prvim godinama isporučili smo desetke kuća širom regije dok smo usavršavali naše metode dizajna i montaže. Ovaj rani uspjeh postavio je temelje za stalni rast i inovacije.",
        paragraph2: "Naša inspiracija proizašla je iz svjedočenja utjecaja na okoliš i otpada koje stvara konvencionalno gradilište. Vidjeli smo priliku da preispitamo gradnju kao proces proizvodne trake, smanjujući rad na gradilištu i otpada materijala. Usvajanjem recikliranih čeličnih okvira i niskougljičnih betonskih panela, minimalizirali smo otpad bez kompromisa u strukturalnoj izvedbi. Ova predanost ekološki prihvatljivim praksama i dalje usmjerava svaki projekt koji poduzmemo.",
        paragraph3: "Tijekom posljednjeg desetljeća neprestano smo unapređivali naše tvorničke procese naprednom automatizacijom i strogom kontrolom kvalitete. Proširili smo portfelj kako bismo uključili prilagođene rasporede, energetski učinkovite tehnologije i integracije pametnih kuća. Stotine zadovoljnih vlasnika kuća uselile su u svoje montažne domove brže i s manje kašnjenja nego ikad prije. U budućnosti ostajemo posvećeni pomicanju granica održivog dizajna i korisničkog iskustva."
      },
      "stats": {
        "clients": "112+",
        "clients_label": "Zadovoljni vlasnici",
        "projects": "85+",
        "projects_label": "Završenih projekata",
        "support": "500+",
        "support_label": "Sati savjetovanja",
        "workers": "25",
        "workers_label": "Članova tima"
      },
      "projects": {
        "title": "Projekti",
        "filter": {
          "all": "Svi",
          "family": "Obiteljske Kuće",
          "tiny": "Male Kućice",
          "beach": "Kuće na Moru",
          "eco": "Eko Vile"
        }
      },
      benefits: {
        title: "Zašto graditi korak po korak?",
        item1: {
          title: "Financijska fleksibilnost",
          desc: "Umjesto da unaprijed plaćate jednoj tvrtki cijeli projekt, raspodjela gradnje u fazama omogućuje vam upravljanje novčanim tokom postepeno. Započinjete s temeljima i montažom konstrukcije, zatim možete privremeno zaustaviti radove kako biste preusmjerili sredstva ili pregovarali o financiranju prije završnih radova. Nedovršena — ali postojeća — struktura ima znatno veću vrijednost za kreditiranje od same ideje o kući."
        },
        item2: {
          title: "Troškovna učinkovitost",
          desc: "Turn-key paketi uključuju skrivene marže kod svakog podizvođača — projektiranje, priprema terena, komunalije, završni radovi. Sami birajući izvođače za svaku fazu, možete odabrati najbolje ponude i kontrolirati kvalitetu. Još bolje: obavite manje radove sami kako biste uštedjeli na radnoj snazi i ponovno iskoristili materijale za štedljiviju gradnju."
        },
        item3: {
          title: "Kvaliteta i specijalizacija",
          desc: "Izvođači koji rade “sve i svašta” ne mogu parirati stručnosti specijaliziranih proizvođača montažnih panela ili krovnih konstrukcija. Usavršili smo proizvodnju pomoću naprednih CAD/CAM alata i preciznih kontrola — tako da znate da je svaki zid, greda i spoj izveden prema najvišim standardima. Isto tako, angažiranje specijalista za električne, vodovodne i vanjske radove osigurava vrhunsku izvedbu svakog zanata."
        },
        item4: {
          title: "Vlasnička kontrola i prilagodba",
          desc: "Vi ste glavni voditelj projekta. Provjerite ravnost temelja prije montaže, dokumentirajte elektro i vodovodne instalacije prije postavljanja zidova i potvrđujte pričvršćenje krova prije izolacije. Što se tiče tlocrta ili završnih radova — mijenjajte raspored prostorija, povećavajte otvore ili birajte vlastitu paletu materijala. Gradnja korak po korak osigurava da vaš dom u potpunosti odražava vašu viziju."
        }
      },
      tabs: {
        modisit: "Modisit",
        praesenti: "Praesenti",
        explica: "Explica",
        nostrum: "Nostrum"
      },
      services: {
        title: "Usluge",
        item1: {
          title: "Dizajn i Planiranje",
          desc: "Prilagođeni arhitektonski rasporedi i 3D modeli prema vašoj lokaciji i budžetu."
        },
        item2: {
          title: "Tvornicka Proizvodnja",
          desc: "Precizna proizvodnja u kontroliranim uvjetima za nulti otpad i vrhunsku kvalitetu."
        },
        item3: {
          title: "Montaža na Lokaciji",
          desc: "Potpuna montaža u danima, obavljena od strane našeg certificiranog tima."
        },
        item4: {
          title: "Energetska Certifikacija",
          desc: "Savjetovanje o pasivnom dizajnu, integraciji solarnih sustava i niskoj potrošnji energije."
        },
        item5: {
          title: "Integracija Pametnih Kuća",
          desc: "Bešavno integriranje automatizacije, sigurnosnih i zabavnih sustava u vaš modularni dom."
        },
        item6: {
          title: "Opcije Prilagodbe",
          desc: "Odaberite prilagođene rasporede, završne obrade i značajke prema vašim potrebama."
        }
      },
      constructions: {
        title: "Izgradnje",
        item1: { title: "Stavka Jedna", desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit." }
      },
      footer: { copy: "© 2025 Montažne Kuće. Sva prava pridržana." }
    }
  }
};

$(document).ready(function () {
  i18next.init({
    lng: 'en',
    debug: false,
    resources: resources
  }, function () {
    jqueryI18next.init(i18next, $, { useOptionsAttr: true });
    $('body').localize();
  });

  $('#lang-en').on('click', function (e) {
    e.preventDefault();
    i18next.changeLanguage('en', function () {
      $('body').localize();
    });
  });

  $('#lang-hr').on('click', function (e) {
    e.preventDefault();
    i18next.changeLanguage('hr', function () {
      $('body').localize();
    });
  });
});

(function () {
  'use strict';
  var form = document.getElementById('contactForm');
  form.addEventListener('submit', function (e) {
    e.preventDefault();
    e.stopPropagation();

    // trigger Bootstrap's validation styles
    form.classList.add('was-validated');

    // if form is valid, show thank-you pop-up
    if (form.checkValidity()) {
      alert('Thank you for reaching out! We will contact you as soon as possible.');
      form.reset();
      form.classList.remove('was-validated');
    }
  }, false);
})();
